# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cc40443ff258543e642bab486427f0486e7031fe5435b410ffa89e9096f20b859458ecb47b47c60e98e1971eae8e9d165a90271496a5b95284b39f68cb3f03cb

test:
  secret_key_base: 99ad7e0df7ee39ba0fb7fc29b9843d634af4cd2cfb697e7947690f3eca41535fe572ce1fdbd0d374674284c03b64b585ff9e989be91ac4af4ab9f20291b01877

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
